# Generated by Django 3.0.2 on 2020-06-08 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mod_date',
        ),
        migrations.AddField(
            model_name='ordered',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
