# Generated by Django 3.0.2 on 2020-06-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200608_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
