# Generated by Django 3.0.2 on 2020-06-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_orderedproduct_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='multiprice',
            field=models.ManyToManyField(default='none', to='backend.MultiplePrice'),
        ),
    ]
