# Generated by Django 3.0.2 on 2020-06-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200615_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multipleprice',
            options={'verbose_name': 'MultiplePrice', 'verbose_name_plural': 'MultiplePrices'},
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
